### ISSUE TITLE
Traefik configuration

### ISSUE THREAD

**Issue by RosaEinhorn** [Ravinou/borgwarehouse#225]
Hello,

I am using borgwarehouse for quite some time now and I am very happy with it. It looks nice and is super reliable. I have been using Caddy as a reverse proxy with little changes to the docker-compose.yaml:

`    ports:
      #- "${WEB_SERVER_PORT:?WEB_SERVER_PORT variable missing}:3000"
      - "${SSH_SERVER_PORT:?SSH_SERVER_PORT variable missing}:22"`

I commented out the GUI port and reverse proxied to `borgwarehouse:3000`.

This configuration works as expected, but I am now migrating all services to Traefik. Unfortunately, I cannot make this run, as I cannot access the borgwarehouse GUI via my proxy network. `borgwarehouse:3000` or `<docker-network-ip>:3000` are not reachable. It does not look like Traefik issue to me, as none of the containers in the proxy network can reach borgwarehouse.

Has anyone setup borgwarehouse with Traefik as a reverse proxy successfully? Thanks a lot in advance. :)

**Comment by RosaEinhorn** [comment]
My proxy (docker)  network has IPv6 enabled. The borgwarehouse log shows that the port is bound to the IPv6 and not the IPv4. However the docker dns lookup point to the IPv4. Is it possible to force borgwarehouse to bind the port to IPv4?

**Comment by Ravinou** [comment]
Thanks for the first words of your first comment. It's very encouraging for me :)

I imagine it's possible to do this by modifying the docker configuration. I don't know if I can do anything at the application level for that? I use ipv4 on a server and it works.

**Comment by c-yco** [comment]
I had a running traefik configuration, but apparently ran in the same issue now. 
Will try to find out whats the issue, and put an update here if I got it working

**Comment by c-yco** [comment]
This i my compose file:
```` yaml
version: '3'
services:
  borgwarehouse:
    #container_name: borgwarehouse
  
    restart: always
    container_name: borgwarehouse
    # If you want to build the image yourself, uncomment the following lines and comment the image line
    #build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #       - UID=${UID}
    #       - GID=${GID}
    image: borgwarehouse/borgwarehouse
    user: "${UID:?UID variable missing}:${GID:?GID variable missing}"
    expose:
      - 3000
      - 22
    env_file:
      - .env
    volumes:
      - ${CONFIG_PATH:?CONFIG_PATH variable missing}:/home/borgwarehouse/app/config
      - ${SSH_PATH:?SSH_PATH variable missing}:/home/borgwarehouse/.ssh
      - ${SSH_HOST:?SSH_HOST variable missing}:/etc/ssh
      - ${BORG_REPOSITORY_PATH:?BORG_REPOSITORY_PATH variable missing}:/home/borgwarehouse/repos
      - ${TMP_PATH:?TMP_PATH variable missing}:/home/borgwarehouse/tmp
      - ${LOGS_PATH:?LOGS_PATH variable missing}:/home/borgwarehouse/logs
    labels:
      # https
      - "traefik.enable=true"
      - "traefik.http.routers.borgwarehouse.rule=Host(`mydomain`)"
      - "traefik.http.routers.borgwarehouse.entrypoints=websecure"
      - "traefik.http.routers.borgwarehouse.tls=true"
      - "traefik.http.routers.borgwarehouse.tls.certresolver=letsencrypt"
      - "traefik.http.services.borgwarehouse.loadbalancer.server.port=3000"
      # ssh
      - "traefik.tcp.routers.borgwarehouse.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.borgwarehouse.service=borgwarehouse@docker"
      - "traefik.tcp.routers.borgwarehouse.entrypoints=tcp_ssh"
      - "traefik.tcp.services.borgwarehouse.loadbalancer.server.port=22"

    networks:
      - traefik_default
      - borgwarehouse
     
  apprise:
    container_name: apprise
    image: caronc/apprise
    user: "www-data:www-data"
    networks:
      - borgwarehouse

networks:
  borgwarehouse:
  traefik_default:
    external: true




````
