### ISSUE TITLE
Attempting to install on Truenas Scale throws error

### ISSUE THREAD

**Issue by epicfacethe3rd** [Ravinou/borgwarehouse#410]
i will be honest - i have no idea what i'm doing here. I did see someone else was able to get it running on scale (I belive @toeirei ?) and would appreciate any guidance you can offer
currently the error i'm getting is this
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 509, in run
    await self.future
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 556, in __run_body
    rv = await self.middleware.run_in_thread(self.method, *args)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1367, in run_in_thread
    return await self.run_in_executor(io_thread_pool_executor, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1364, in run_in_executor
    return await loop.run_in_executor(pool, functools.partial(method, *args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/service/crud_service.py", line 268, in nf
    rv = func(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 55, in nf
    res = f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 183, in nf
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 203, in do_create
    return self.create_internal(job, app_name, version, data['values'], complete_app_details)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 248, in create_internal
    raise e from None
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/crud.py", line 241, in create_internal
    compose_action(app_name, version, 'up', force_recreate=True, remove_orphans=True)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/apps/compose_utils.py", line 61, in compose_action
    raise CallError(err_msg)
middlewared.service_exception.CallError: [EFAULT] Failed 'up' action for 'borgwarehouse' app. Please check /var/log/app_lifecycle.log for more details

```

**Comment by Ravinou** [comment]
Hi, I don't know trueNAS at all, but I know that several people use it with BorgWarehouse. Have you researched the issues?

**Comment by ToeiRei** [comment]
Yup, I got it running and that error looks familiar.

Here is a quick rundown of the settings I use:

## Image configuration
- image repo: borgwarehouse/borgwarehouse
- tag: latest
- pull policy: always pull

The pull policy does not mitigate the unwillingness of scale to auto-update custom apps. watchtower breaks stuff!

## Container configuration
- hostname: (none)
- entrypoint: (none)
- command: (none)
- timezone: (your timezone)

### Environment variables:
- FQDN: your.borg.name.that.you.proxy
- UID: (user on scale used for the volume)
- GID: (group on scale used for the volume)
- MAIL_SMTP_HOST: (optional - see docs)
- MAIL_REJECT_SELFSIGNED_TLS: (optional - see docs)
- UNIX_USER: borgwarehouse
- NEXTAUTH_URL: (http://ip:port of the nas where bw is exposed)
- SSH_SERVER_PORT: 2222 (cannot be 22!)

## container config (continued)
- restart policy: unless stopped
- disable builtin healthcheck: unchecked
- tty: unchecked
- stdin: unchecked

## Security Context Config:
- privileged: unchecked
- Caps: (none)
- Custom user: UID and GID from Environment variables

## Network Configuration
- host network: unckecked
- 3000:3000/TCP
- 22:2222/TCP (see environment variables!)

custom DNS is not set at all

## Portal Configuration
- Name: Web UI
- Protocol: HTTP
- Hots: NAS IP
- Port: 3000 (see env.)
- Path: /

## Storage Config
### first storage for configs
- type: Host Path
- mount path: /home/borgwarehouse/app/config
- acl: unchecked
- host path: dealers choice

### second storage for ssh keys
- type: Host Path
- mount path: /home/borgwarehouse/.ssh
- acl: unchecked
- host path: dealers choice

### third: sshd config
- type: Host Path
- mount path: /etc/ssh
- acl: unchecked
- host path: dealers choice

### finally: backup storage
- type: Host Path
- mount path: /home/borgwarehouse/repos
- acl: unchecked
- host path: dealers choice

I also added tmp and logs storage similar:

tmpfs for /home/borgwarehouse/tmp
host path for /home/borgwarehouse/logs


This should get you up and running @epicfacethe3rd 
@Ravinou feel free to abuse this as documentation

**Comment by ToeiRei** [comment]
Main problem for TrueNAS is that the error messages are not 'clear'. You get a ton of python junk instead of an actual error message. Poking around in the actual error log is pretty unknown :)

**Comment by Ravinou** [comment]
Nice, thank you @ToeiRei ! I will add this to documentation. If you have some screenshots, it will be nice. I imagine the steps you describe are configuration screens?

**Comment by ToeiRei** [comment]
Yes - the fields are labeled accordingly as I went through the whole config as soon as I saw the issue being opened and my name mentioned.

![Image](https://github.com/user-attachments/assets/0f2b1518-acd5-4056-b0b3-9769a6d5f200)

**Comment by epicfacethe3rd** [comment]
thank you so much! i'll give this a go later this weekend

**Comment by epicfacethe3rd** [comment]
![Image](https://github.com/user-attachments/assets/a9d95001-7017-4f57-90ad-a650ad5efb2f)
Attached output

**Comment by ToeiRei** [comment]
An easy UID/GID would be 1001 - make sure to use that for a user on your truenas as well, as well as your volume permissions!

**Comment by epicfacethe3rd** [comment]
@ToeiRei way ahead of you there - the only thing i can think of is maybe truenas auto shortening the username is messing with it somehow?
![Image](https://github.com/user-attachments/assets/6ffbeb45-eced-414d-9ada-094586fd03ef)

![Image](https://github.com/user-attachments/assets/77b6b1bb-d42b-42a9-b4c5-226f24f6b8b7)

![Image](https://github.com/user-attachments/assets/ceb536f2-293f-42b9-8c0c-5f2ecb566d31)

**Comment by epicfacethe3rd** [comment]
also, thanks for the super quick reply!

**Comment by epicfacethe3rd** [comment]
should also note - tried also using UNIX_USER to `borgware` (what truenas shortened it to), no dice

**Comment by epicfacethe3rd** [comment]
it is at least saving the container and allowing me to read the log files as well, which is a huge step from what it was earlier. Plus knowing someone else has gotten it working on Scale is super encouraging

**Comment by epicfacethe3rd** [comment]
![Image](https://github.com/user-attachments/assets/1b07e376-d75b-4316-aa35-5aa99eaa6bef)
I am an idiot!
thank you for your patience. The rest of the config did work @ToeiRei and it seems to be running fine now!
i will try to remember to make a pr to add this as documentation because seeing someone else who got it running made life WAY easier

**Comment by Ravinou** [comment]
I just add this thread **to the FAQ of BorgWarehouse doc**.

Thank you again @ToeiRei for your help 🙏

**Comment by ToeiRei** [comment]
@Ravinou Thank you as well for writing this piece of software.

**Comment by parkan** [comment]
@ToeiRei would you be willing to post the yaml definition of the container for easier sharing?

**Comment by ToeiRei** [comment]
> [@ToeiRei](https://github.com/ToeiRei) would you be willing to post the yaml definition of the container for easier sharing?

Where would I get the yaml from?

**Comment by parkan** [comment]
> > [@ToeiRei](https://github.com/ToeiRei) would you be willing to post the yaml definition of the container for easier sharing?
> 
> Where would I get the yaml from?

it should be something like `/mnt/.ix-apps/app_configs/borgwarehouse/versions/0.0.0.1/ix_values.yaml` where `borgwarehouse` is what you called the app and `0.0.0.1` is the version shown in the UI

 I don't currently have any custom apps installed so not 100% sure but somewhere under `/mnt/.ix-apps/app_configs/borgwarehouse/` there should be something that looks like a docker-compose file

**Comment by ToeiRei** [comment]
The only thing I can provide that looks like actual data in there (without just empty arrays and stuff) is the user_config.yaml:

```yaml

TZ: Europe/Vienna
capabilities:
  add: []
command: []
devices: []
disable_builtin_healthcheck: false
dns_config:
  nameservers: []
  options: []
  searches: []
entrypoint: []
envs:
- name: FQDN
  value: borg.stargazer.systems
- name: NEXTAUTH_SECRET
  value: foo
- name: CRONJOB_KEY
  value: bar
- name: UID
  value: '1001'
- name: GID
  value: '1001'
- name: MAIL_SMTP_FROM
  value: borg@example.com
- name: MAIL_SMTP_HOST
  value: mail.example.com
- name: MAIL_SMTP_PORT
  value: '25'
- name: MAIL_REJECT_SELFSIGNED_TLS
  value: 'false'
- name: UNIX_USER
  value: borgwarehouse
- name: NEXTAUTH_URL
  value: http://X.Y.Z.A:3000/
- name: SSH_SERVER_PORT
  value: '2222'
host_network: false
hostname: ''
image:
  pull_policy: always
  repository: borgwarehouse/borgwarehouse
  tag: latest
ix_certificate_authorities: {}
ix_certificates: {}
ix_context:
  app_metadata: &id001
    app_version: 1.0.0
    capabilities: []
    categories:
    - custom
    description: An application for deploying simple containers.
    home: https://www.truenas.com/
    host_mounts: []
    icon: https://media.sys.truenas.net/apps/ix-chart/icons/icon.webp
    keywords: []
    lib_version: 2.1.16
    lib_version_hash: dac15686f882b9ce65b8549a3d5c0ed7bafe2df7a9028880d1a99b0ff4af1eff
    maintainers:
    - email: dev@ixsystems.com
      name: truenas
      url: https://www.truenas.com/
    name: ix-app
    run_as_context: []
    screenshots: []
    sources: []
    title: iX App
    train: stable
    version: 1.1.12
  app_name: borgwarehouse
  is_install: false
  is_rollback: false
  is_update: false
  is_upgrade: true
  operation: UPGRADE
  upgrade_metadata:
    new_version_metadata: *id001
    old_version_metadata:
      app_version: 1.0.0
      capabilities: []
      categories:
      - custom
      description: An application for deploying simple containers.
      home: https://www.truenas.com/
      host_mounts: []
      icon: https://media.sys.truenas.net/apps/ix-chart/icons/icon.webp
      keywords: []
      lib_version: 2.1.14
      lib_version_hash: 982057eeec3024ccecbeaa70e9ee59d948523a3b29d9fca6b39f127a42caa1cc
      maintainers:
      - email: dev@ixsystems.com
        name: truenas
        url: https://www.truenas.com/
      name: ix-app
      run_as_context: []
      screenshots: []
      sources: []
      title: iX App
      train: stable
      version: 1.1.10
ix_volumes: {}
labels: []
portals:
- host: X.Y.Z.A
  name: Web UI
  path: /
  port: 3000
  scheme: http
  use_node_ip: false
ports:
- protocol: tcp
  published: 3000
  target: 3000
- protocol: tcp
  published: 2222
  target: 22
privileged: false
release_name: borgwarehouse
resources:
  enable_resource_limits: false
  gpus:
    nvidia_gpu_selection: {}
    use_all_gpus: false
restart_policy: unless-stopped
run_as:
  group: 1001
  user: 1001
run_as_custom_user: true
stdin: false
storage:
- host_path_config:
    acl_enable: false
    path: /mnt/MyPool/Backup/borgmatic/config
  mount_path: /home/borgwarehouse/app/config
  read_only: false
  type: host_path
- host_path_config:
    acl_enable: false
    path: /mnt/MyPool/Backup/borgmatic/ssh
  mount_path: /home/borgwarehouse/.ssh
  read_only: false
  type: host_path
- host_path_config:
    acl_enable: false
    path: /mnt/MyPool/Backup/borgmatic/sshd_config
  mount_path: /etc/ssh
  read_only: false
  type: host_path
- host_path_config:
    acl_enable: false
    path: /mnt/MyPool/Backup/borgmatic/repos
  mount_path: /home/borgwarehouse/repos
  read_only: false
  type: host_path
- mount_path: /home/borgwarehouse/tmp
  read_only: false
  tmpfs_config:
    size: 500
  type: tmpfs
- host_path_config:
    acl_enable: false
    path: /mnt/MyPool/Backup/borgmatic/logs
  mount_path: /home/borgwarehouse/logs
  read_only: false
  type: host_path
tty: false
```

replaced some values for privacy reasons here.
