### ISSUE TITLE
docker deployment works for LAN, remote machines ask for borgwarehouse user's password

### ISSUE THREAD

**Issue by hugalafutro** [Ravinou/borgwarehouse#61]
Hi,
I finally successfully switched from bare-metal to docker deployment, added my local machines and successfully performed backup with borgmatic running in docker as well.

Next I proceeded to add my remote machines, however herein lies the issue, where these will ask for password of user `borgwarehouse` preventing me from continuing

trying to init repo from remote machine:
```
The authenticity of host '[REDACTED]:2223 ([REDACTED]:2223)' can't be established.
ED25519 key fingerprint is SHA256:REDACTED
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Remote: Warning: Permanently added '[REDACTED]:2223' (ED25519) to the list of known hosts.
borgwarehouse@[REDACTED]'s password:
```

my `docker-compose.yml`
```
version: "3"
services:
  borgwarehouse:
    container_name: borgwarehouse
    build:
       context: .
       dockerfile: Dockerfile
    user: "1001:1001"
    ports:
      - "3000:3000"
      - "2223:22"
    environment:
      - NEXTAUTH_URL=http://192.168.1.227:3000
      - MAIL_SMTP_FROM=borgwarehouse@pi-docker.lan
      - MAIL_SMTP_HOST=[REDACTED]
      - MAIL_SMTP_PORT=587
      - MAIL_SMTP_LOGIN=[REDACTED]
      - MAIL_SMTP_PWD=[REDACTED]
      - MAIL_REJECT_SELFSIGNED_TLS=true
      - NEXT_TELEMETRY_DISABLED=1
      - SSH_SERVER_PORT=2223
      - FQDN=[REDACTED]
      - FQDN_LAN=192.168.1.227
      - SSH_SERVER_PORT_LAN=2223

    volumes:
      - ./config:/home/borgwarehouse/app/config
      - ./ssh:/home/borgwarehouse/.ssh
      - ./ssh_host:/etc/ssh
      - /var/borgwarehouse:/home/borgwarehouse/repos
```
