### ISSUE TITLE
Docker Deployment Fails with User/Group Configuration other than 1001:1001

### ISSUE THREAD

**Issue by nosbig** [Ravinou/borgwarehouse#94]
On a Linux Docker install, without Docker Desktop, a deployment of BorgWarehouse with another UID and/or GID fails, as the container image is built with the borgwarehouse containing the user borgwarehouse (1001) and the group borgwarehouse (1001).

Apparently, Docker Desktop does rebuild the container such that it runs and adjusts the permissions somewhere (either at the host or from within the container), but the standard Docker daemon does no adjustments to permissions.

I've been trying to dabble with building my own image, which I can do by modifying the Dockerfile to add the UID and GID directly into the Dockerfile as well as adding support for changing the UID and GID from the base image at runtime:

RUN usermod --uid ${UID} borgwarehouse
RUN groupmod --gid ${GID} borgwarehouse

I've not been able to get it to build with any other combination of changes to the docker-compose.yml file or .env to pass along those values dynamically to the build, much less during a standard Docker Compose deployment.

This feels like it's similar to #60.

**Comment by Ravinou** [comment]
Thank you for your issue. I manage to reproduce the problem without docker desktop. I'm looking for the right solution.

**Comment by shad-lp** [comment]
I can confirm this behaviour, I am trying to set my Synology NAS as my main Borg repo host, using that compose :

```
version: "2.1"
services:

   borgwarehouse:
      image: borgwarehouse/borgwarehouse
      container_name: borgwarehouse
      network_mode: bridge
      user: "1031:100"
      environment:
         - NEXTAUTH_URL=https://bwh.xxx.ovh
         - NEXTAUTH_SECRET=VKXHRqnwH2o6xEJCYD77JR4tmacLTWP2YldapIq7dyE=
         - CRONJOB_KEY=Z8Da8Ao6SwRY0JNiE9nVEh4+GZYrFMYqxJjb5nQmMGY=
         - SSH_SERVER_PORT=50022
         - FQDN=bwh.xxx.ovh
         # backup through LAN
         - SSH_SERVER_PORT_LAN=50022
         - FQDN_LAN=garrus.xxx.ovh
      ports:
         - 53000:3000/tcp
         - 50022:22/tcp
      volumes:
         # config
         - /volume1/homes/backup/borgwarehouse-data/config:/home/borgwarehouse/app/config
         - /volume1/homes/backup/borgwarehouse-data/ssh:/home/borgwarehouse/.ssh
         - /volume1/homes/backup/borgwarehouse-data/ssh_host:/etc/ssh
         - /volume1/backup/borgwarehouse-repos:/home/borgwarehouse/repos
      labels:
         # watchtower label only monitoring
         - "com.centurylinklabs.watchtower.enable=true"
      restart: unless-stopped
```

Logs at first deployment :

```
2023-11-18T08:45:55.599477410Z /etc/ssh is empty, generating SSH host keys...
2023-11-18T08:45:55.872282997Z No user exists for uid 1031
2023-11-18T08:46:10.504435157Z /etc/ssh is empty, generating SSH host keys...
2023-11-18T08:46:10.508812955Z No user exists for uid 1031
2023-11-18T08:46:21.259399199Z /etc/ssh is empty, generating SSH host keys...
2023-11-18T08:46:21.417330542Z No user exists for uid 1031
```

1031 is the UID of my dedicated backup user on Synology DSM
100 is the default GID every user (mandatory) belongs to.

Permissions on folders :

![image](https://github.com/Ravinou/borgwarehouse/assets/43928955/ee092df6-6c0f-473b-a7d7-ea85003c7b08)
![image](https://github.com/Ravinou/borgwarehouse/assets/43928955/5f420372-f2e9-4585-b2e6-af84fac16143)

By the way thanks for your awesome work to improve this software since my first issue to tell you about Apprise.
I'd gladly sponsor your work if you enable the feature.
